project:
  type: website
  output-dir: docs

website:
  title: "West Coast Neuroecon"
  favicon: images/favicon.png
  search: false
  navbar:
    background: primary
    foreground: light
    search: false
    right:
      - text: "Register"
        href: "https://forms.gle/qsXzPKDpUPiYEhgcA"
  page-footer:
    left: |
      West Coast Neuroecon &copy; 2026
    center: |
      Hosted by UCLA
    right: |
      [Contact Us](mailto:wcneuroecon@gmail.com)

format:
  html:
    theme:
      - cosmo
      - styles/custom.scss
    css: styles/styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    code-copy: false
    code-tools: false
